### ISSUE TITLE
"runGprimeAnalysis" cannot  work well

### ISSUE THREAD

**Issue by xuxuda** [bmansfeld/QTLseqR#11]
QTLseq analysis can be successfully runned and get the good QTL analysis plots. Howerver, when  I try to 
extract significant regions using "getSigRegions", I was told the following warnings:
**"Error in****getSigRegions(SNPset = df_filt, alpha = 0.01) : Please first use runGprimeAnalysis to calculate q-values".**
Thus, I run **"> df_filt <- runGprimeAnalysis(SNPset = df_filt, windowSize = 2e8, outlierFilter = "deltaSNP")"**
Then more warnings coming.........

**Counting SNPs in each window...
Calculating tricube smoothed delta SNP index...
Calculating G and G' statistics...
Using deltaSNP-index to filter outlier regions with a threshold of 0.1
Estimating the mode of a trimmed G prime set using the 'modeest' package...
Error in mutate_impl(.data, dots) : 
  Evaluation error: $ operator is invalid for atomic vectors.**
 May you give me some advices ?

**Comment by bmansfeld** [comment]
Thanks for the comments.
If you want significant regions for QTLseq please set the `method = "QTLseq"` in `getSigRegions()`.
Also make sure to set the `interval` parameter. See `?getSigRegions` for help.

In regard to the Gprime errors. I am aware of this bug due to a recent change in the `modeest` package.
Thanks for flagging this.
I will fix it this weekend, for now you can downgrade `modeest` to version 2.1 and it should work.
Thanks again,
Ben

**Comment by xuxuda** [comment]
Thanks for your reply! It actually is the problem of the "modeest" package but I fail to fix it. Waiting for you to fix the bug.
Best wishes!

Dengan

**Comment by bmansfeld** [comment]
Ok this has been fixed in QTLseqr v0.7.4.
Good luck with your work!
