### ISSUE TITLE
Issue with plotQTLstat

### ISSUE THREAD

**Issue by Coradini03** [bmansfeld/QTLseqR#13]
Hi Ben,

I am new user of QTLseqr,  but it seems a really nice package!! Congrats!!
However, I  got an error when trying to plot graphs from plotQTLstat as described above.

p2 <- plotQTLStats(SNPset = data_filt, var = "deltaSNP", plotIntervals = TRUE)
p2
**Error in f(..., self = self) : Breaks and labels are different lengths
In addition: Warning message:
In x/limits[i] :
  longer object length is not a multiple of shorter object length**

I am trying to plot a yeast QTL analysis having 16 chromossomes with distinct sizes. 
By using  subset() and manualy adding the chromossomes I figured out that  I got the graph when I exclude the two majors chromossomes > 1Mb. 
So seems the error happens when one of these "large" chromossomes is on my plot. 

Do you know how to fix it? Sorry if the question sounds idiot.

Best,

Alessandro

**Comment by bmansfeld** [comment]
Hey Allesandro,
Thanks for the feedback!
I'm guessing the error is due to some formatting of the x axis.. I wasn't anticipating users in yeast or other organisms with smaller genomes (I'm a plant guy).
If you send me your data I could take a look to understand why it breaks the code. I have some ideas but it's hard to be sure with out an example.
In any case you really don't need for me to solve this for you. plotQTLStats is just a wrapper for ggplot and all the data for plotting exists in your data_filt dataframe. So you can reproduce the plots manually using that. 
Ben
