### ISSUE TITLE
What's the increment of the sliding window analysis?

### ISSUE THREAD

**Issue by Jifeng87** [bmansfeld/QTLseqR#23]
Dear Ben,
     I am trying to use the QTLseqr to treat my bulked data for a rice QTL-seq analysis. In your example of rice study, you showed the fixed size (1000kb) of the sliding window analysis but didn't mention the increment of the sliding window. In Takagi's paper, they chose the window size as 2Mb with 10kb increment to apply the sliding window analysis. Could you tell me the increment size in the rice example? Or how can I set the sliding window increment size? Thank you very much.
Sincerely
Jifeng

**Comment by bmansfeld** [comment]
Hi Jifeng,
QTLseqr uses a slightly different smoothing approach which helps mitigate problems with empty windows.
Instead of using a standard sliding window (which averages all values within it) we opted for a tricube-smoothing kernel approach. In this approach the center of each window is a snp and the window jumps from snp to snp with out a step size. Each window has to have a snp in it's center. The other thing this does is smooth the data in a way that snps distant to the focal (center) snp have a lesser affect on the average. 
For more information please read the QTLseqr manuscript (lots of info in the supplemental file) as well as Magwene et al., 2011 (for a more in depth understanding). 
Hope that helps.
Ben

**Comment by Jifeng87** [comment]
Dear Ben,
     Thank you for reply. It is so helpful. I will read the manuscript and Magwene et al., 2011 carefully. I really appreciate your help.
Sincerely
Jifeng

**Comment by bmansfeld** [comment]
Great to hear. 
Good luck with your work.
Ben
