### ISSUE TITLE
No QTL signal when running runQTLseqAnalysis() but a clear signal when running runGprimeAnalysis()

### ISSUE THREAD

**Issue by kostasgalexiou** [bmansfeld/QTLseqR#53]
Hi,

When I run the Takagi method I get no singal at all. Below you have the command that I am running

```
df_filt_qtlseq <- runQTLseqAnalysis(df_filt, windowSize = 5e6,
                                    popStruc = "F2",
                                    bulkSize = c(14, 14),
                                    replications = 10000,
                                    intervals = c(95, 99))

plotQTLStats(SNPset = df_filt_qtlseq, var = "deltaSNP", plotIntervals = TRUE) + 
  ggtitle('deltaSNP - 5Mbp window') + 
  theme(axis.text.x = element_text(angle = 90, size = 6)) + 
  theme(plot.title = element_text(size = 10))
```
with does not give me any significant signal at all: Please see figure: [QTLseqR_deltaSNP_5Mbp.pdf](https://github.com/bmansfeld/QTLseqr/files/9158607/QTLseqR_deltaSNP_5Mbp.pdf)
 
However, running the G prime method, I get a clear signal in chromosome 1.

```
runGprimeAnalysis(SNPset = df_filt, windowSize = 5e6, outlierFilter = "deltaSNP", 
                                    filterThreshold = 0.01)

plotQTLStats(SNPset = df_filt_gprime, var = "Gprime", plotThreshold = TRUE, q=0.01) + 
  ggtitle('Gprime - 5Mbp') +
  theme(axis.text.x = element_text(angle = 90, size = 6)) +
  theme(plot.title = element_text(size = 10))
```
G prime analysis figure: [QTLseqR_Gprime-distribution-deltaSNPoutlierFilter.pdf](https://github.com/bmansfeld/QTLseqr/files/9158624/QTLseqR_Gprime-distribution-deltaSNPoutlierFilter.pdf)

Please let me know if you need any additional information. I am using QTLseqr_0.7.5.2.

Best
Kostas

**Comment by bmansfeld** [comment]
Hey Kostas,
Thanks for the detailed post. 
Sometimes there can be incongruencies between the two methods - this seems counter intuitive since they are essentially using the same numbers, but it can happen sometimes. 

A few questions, ideas and suggestions to evaluate:

- Examine the SNP-index plots for each bulk separately this will help you understand if there is truly and enrichment for one allele or the other in the bulks. 

- You didn't share the Gprime fig (i get it) but it's hard to know how much to trust that signal. Gprime works a bit better with non-plant systems like yeast were it was developed. This is probably because the population sizes are bigger. In any case, if you read Magwene the Gprime values they have for the QTL they report are super high like a value of 40. Often times I've seen signal from Gprime in plant research they are in the range of 15 or less. If you have a peak, even a substantive one with a Gprime of 3 or something like that I would be very suspicious of that. Even if it passes the nonparametric thresholds.

-  Not sure what organism you are working on but if the genome is heterozygous and not accurately phased then deltaSNP can fail around phase switch errors. This is because the genome has both alt and ref alleles mixed in the window and that essentially cancels out the enrichment signal. Gprime will still pick up the signal because it detects absolute deviation from the expected 50:50 allele distribution as apposed to a deviation in a specific direction (hope that I was able to explain that concept - it a bit confusing, but I know it from real life experience).
 

- Window sizes are important. I see you have 5Mb size but some of your chroms are 100Mb. Magwene recommends a 20cM window for Gprime. Usually in deltaSNP with have smaller windows like 1, 2 or 5 Mb like you selected. I'm guessing in your organism with 100Mb chrom 5 cM is not 20cM. So if you really chose a larger window as recomended in the Magwene MS then your signal will go away.

Those are my best suggestions. 
Seems like you might need to go back to the population and double check the phenotyping. Unfortunately that is still the main bottle neck. If you can develop a large population with a few more individuals to increase your bulk size then you will hopefully be able to trust the results a bit better. 
14 / bulk isn't terrible (i've worked with less) but it helps if you have 20 or a bit more.
another option is to use F3s that helps enrich for homozygotes which strengthens the signal (less hets = stronger SNP-index in the bulk).

Hope that helps a bit, 
Ben

**Comment by kostasgalexiou** [comment]
Hi Ben,

Thank you for your extensive reply. The G' peak is close to 17. Below is the correct figure.

[QTLseqR_Gprime-deltaSNP-outlierFilter.pdf](https://github.com/bmansfeld/QTLseqr/files/9165470/QTLseqR_Gprime-deltaSNP-outlierFilter.pdf)

I will follow the advice you gave me at point 1 to check the SNP index distribution in both bulks separately. Most probably you are right (point 3 and end of your reply) about why deltaSNP is not showing any signal, since my parents are heterozygous (I am working with cannabis) and the trait I am looking at is dominant. Actually, when I zoom in at the G' peak in chromosome 1, I can see that the deltaSNP value is around 0.6 with the SNP-low index being 0 and the SNP-high at around 0.5. This means that SNPs at the QTL are heterozygous in the high bulk.

Please fill free to close the issue. In any case, if you wish, I can update you on my findings regarding the SNP-index dist in the 2 bulks

Best,
Kostas

**Comment by bmansfeld** [comment]
Kostas, 
Happy some of my comments helped/made sense. 
Good luck with your mapping!! 
I'll close this issue but if you would like to post any other insights im sure other people might be interested our curious.
Thanks for using QTLseqr.
Ben
