### ISSUE TITLE
Issue with CI names

### ISSUE THREAD

**Issue by cheesemania** [bmansfeld/QTLseqR#57]
Hi, great tool!

I can run G prime analysis absolutely fine, but I get an issue with the deltaSNP analysis around the CI simulations. Can you shed any light on whats going on?

Thanks

Ian

> df_filt<-runQTLseqAnalysis(df_filt,bulkSize=100,windowSize=200000,filter=0.1)
Counting SNPs in each window...
Calculating tricube smoothed delta SNP index...
Returning the following two sided confidence intervals: 95, 99
Variable 'depth' not defined, using min and max depth from data: 150-150
Assuming bulks selected from F2 population, with 100 individuals per bulk.
The 'bulkSize' argument is of length 1, setting number of individuals in both bulks to: 100
Simulating 10000 SNPs with reads at each depth: 150-150
Keeping SNPs with >= 0.1 SNP-index in both simulated bulks
Error in names(CI) <- paste0("CI_", 100 - (intervals * 200)) : 
  'names' attribute [2] must be the same length as the vector [1]

**Comment by bmansfeld** [comment]
Hey,
I'm not sure what's going on, but I'm guessing it has something to do with the fact the the min and max depth are equal (150). 
That's kinda funny? did you filter the data to only include SNPs of that depth?
alternatively play around with the filter perimeter? does changing that impact running?
Let me know if that helps, otherwise ill need to see df_filt to see if I can debug.
Ben
